const windowsArray = [
  {
    id: "window-1",
    day: 1,
    source: "images/1.jpg",
    text: "Day 1",
    open: false,
    type: "image",
  },
  {
    id: "window-2",
    day: 2,
    source: "videos/1.mp4",
    text: "Day 2",
    open: false,
    type: "video",
  },
  {
    id: "window-3",
    day: 3,
    source: "images/2.jpg",
    text: "Day 3",
    open: false,
    type: "image",
  },
  {
    id: "window-4",
    day: 4,
    source: "videos/2.mp4",
    text: "Day 4",
    open: false,
    type: "video",
  },
  {
    id: "window-5",
    day: 5,
    source: "images/3.jpg",
    text: "Day 5",
    open: false,
    type: "image",
  },
  {
    id: "window-6",
    day: 6,
    source: "videos/1.mp4",
    text: "day 6",
    open: false,
    type: "video",
  },
  {
    id: "window-7",
    day: 7,
    source: "images/4.jpg",
    text: "Day 7",
    open: false,
    type: "image",
  },
  {
    id: "window-8",
    day: 8,
    source: "videos/2.mp4",
    text: "day 8",
    open: false,
    type: "video",
  },
  {
    id: "window-9",
    day: 9,
    source: "images/5.jpg",
    text: "day 9",
    open: false,
    type: "image",
  },
  {
    id: "window-10",
    day: 10,
    source: "videos/1.mp4",
    text: "day 10",
    open: false,
    type: "video",
  },
  {
    id: "window-11",
    day: 11,
    source: "images/6.jpg",
    text: "day 11",
    open: false,
    type: "image",
  },
  {
    id: "window-12",
    day: 12,
    source: "videos/2.mp4",
    text: "day 12",
    open: false,
    type: "video",
  },
  {
    id: "window-13",
    day: 13,
    source: "images/7.jpg",
    text: "day 13",
    open: false,
    type: "image",
  },
  {
    id: "window-14",
    day: 14,
    source: "videos/1.mp4",
    text: "day 14",
    open: false,
    type: "video",
  },
  {
    id: "window-15",
    day: 15,
    source: "images/8.jpg",
    text: "day 15",
    open: false,
    type: "image",
  },
  {
    id: "window-16",
    day: 16,
    source: "videos/2.mp4",
    text: "day16",
    open: false,
    type: "video",
  },
  {
    id: "window-17",
    day: 17,
    source: "images/9.jpg",
    text: "day 17",
    open: false,
    type: "image",
  },
  {
    id: "window-18",
    day: 18,
    source: "videos/1.mp4",
    text: "day 18",
    open: false,
    type: "video",
  },
  {
    id: "window-19",
    day: 19,
    source: "images/10.jpg",
    text: "day 19",
    open: false,
    type: "image",
  },
  {
    id: "window-20",
    day: 20,
    source: "videos/2.mp4",
    text: "day 20",
    open: false,
    type: "video",
  },
  {
    id: "window-21",
    day: 21,
    source: "images/11.jpg",
    text: "day 21",
    open: false,
    type: "image",
  },
  {
    id: "window-22",
    day: 22,
    source: "videos/1.mp4",
    text: "day 22",
    open: false,
    type: "video",
  },
  {
    id: "window-23",
    day: 23,
    source: "images/12.jpg",
    text: "day 23",
    open: false,
    type: "image",
  },
  {
    id: "window-24",
    day: 24,
    source: "videos/2.mp4",
    text: "day 24",
    open: false,
    type: "video",
  },
  {
    id: "window-25",
    day: 25,
    source: "images/7.jpg",
    text: "day 24",
    open: false,
    type: "image",
  },
];

export default windowsArray;
